# Generated by Django 4.2.2 on 2023-07-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineapedido",
            old_name="pedido_id",
            new_name="pedido",
        ),
        migrations.RenameField(
            model_name="lineapedido",
            old_name="producto_id",
            new_name="producto",
        ),
    ]
